# Generated by Django 5.1.3 on 2025-01-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone', models.BigIntegerField()),
                ('DOB', models.DateField()),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('father_name', models.CharField(max_length=52)),
                ('mother_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=32)),
                ('pin_code', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('balance', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('account_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
