# Generated by Django 5.1.3 on 2025-01-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
